# gradle-plugins-ci.yml 
agents:
  cpu: "4"
  memory: "8G"
  ephemeralStorage: "80G"
  image: pixelgroup/docker-java-git:17-jdk
steps:
  - label: ":pipeline: Gradle Check"
    commands:
    - "./gradlew check"
  #- label: ":pipeline: Build examples: docker-full"
  #  commands:
  #    - "cd examples/docker-full ./gradlew dockerBuild"
  #- label: ":pipeline: Build examples: docker-elastic"
  #  commands:
  #    - "cd examples/docker-elastic ./gradlew dockerBuild"